### ISSUE TITLE
'We Can Code Again' not working

### ISSUE THREAD

**Issue by mikrosk** [cahirwpz/demoscene#1]
Oh, hi, it's me again ;)

As a start, I have chosen to try your nice demo first. So I checked out 934534bdbd8ad373f538952e90c8b31ba8a2f160 (final touches), typed 'make' and voila, output is 107932 bytes long binary. What might be first sign of trouble because the release binary is 103312 bytes long. When I copy this new binary over to the same folder where 'data' is, it seems to start (printing info about Kickstart version, CPU etc) but then it does nothing (no loading screen). So I'm wondering, is there something else I need to do?

I tried also other stuff from 'effects', the ones which do not require any data (particles, 2d vectors, ...) work fine. So startup code & friends must be ok...

**Comment by optixx** [comment]
Would be great if you could provide a dl link for the missing data files. I would like to explore your a500 framework a bit more.
