### ISSUE TITLE
Find missing scripts

### ISSUE THREAD

**Issue by cahirwpz** [cahirwpz/demoscene#19]
Following effects miss a script that was used to generate data for them:
 * [x] ball
 * [x] floor
 * [x] twister-rgb

We need to find those script in old archives!

**Comment by codigtn** [comment]
twister_data.pde has been founded.

**Comment by cahirwpz** [comment]
What about old sushiboyz archives?

**Comment by cahirwpz** [comment]
You gave me a good hint with `twister_data.pde`. I found `floor_data.pde` processing sketch as well!

**Comment by cahirwpz** [comment]
Found the last one!
