### ISSUE TITLE
Toolchain artifact missing

### ISSUE THREAD

**Issue by zedar187** [cahirwpz/demoscene#83]
It seems that circleci.com is deleting artifacts after one month. Thus the Dockerfile can't download the toolchain.tar.gz.

```
There are no artifacts to show here.
After 30 days, all artifacts associated with a build automatically expire. Since this run is over 30 days old, the artifacts may have been deleted.
```

**Comment by cahirwpz** [comment]
Thanks for pointing it out. Fixed in https://github.com/cahirwpz/demoscene/commit/980d2aa89d7574ebeb2f54c1f917bec39e5896d6
